### ISSUE TITLE
New Lightning Flaw

### ISSUE THREAD

**Issue by belav** [davidshares/Lightning-Network#4]
Here is another one for the ever growing list.

https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-October/022032.html

**Comment by davidshares** [comment]
Thank you for the submission, I really appreciate it! However, [I added an update](https://github.com/davidshares/Lightning-Network#2023-and-beyond), as I'm no longer tracking the utter failure that is the Lightning Network, as I believe it is a waste of time and resources. Time could be spent better elsewhere at this point.
